# Generated by Django 3.2 on 2021-11-23 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingridient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
