# Generated by Django 3.2 on 2021-11-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_ingridientinrecipe_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingridientinrecipe",
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
    ]
