# Generated by Django 3.2 on 2021-11-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_ingridientinrecipe_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingridientinrecipe",
            name="ingridient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingridient_in_recipe",
                to="recipes.ingridient",
                verbose_name="Ингредиент",
            ),
        ),
    ]
