# Generated by Django 3.2 on 2021-11-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_rename_ingridient_ingredient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
            },
        ),
    ]
