# Generated by Django 3.2 on 2021-11-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_favorite_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "verbose_name": "Список покупок",
                "verbose_name_plural": "Списки покупок",
            },
        ),
    ]
