# Generated by Django 3.2 on 2021-12-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_alter_shoppingcart_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="text_description",
            new_name="text",
        ),
    ]
