# Generated by Django 3.2 on 2021-12-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_text_description_recipe_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingridientinrecipe',
            old_name='ingridient',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridients',
            new_name='ingredients',
        ),
    ]
